-- MySQL Script generated by MySQL Workbench
-- Sat Jul 19 15:01:25 2014
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema gnw
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gnw` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `gnw` ;

-- -----------------------------------------------------
-- Table `gnw`.`gnw_utilisateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gnw`.`gnw_utilisateur` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(255) NOT NULL,
  `prenom` VARCHAR(255) NOT NULL,
  `adresse_mail` VARCHAR(255) NOT NULL,
  `mot_de_passe` VARCHAR(255) NOT NULL,
  `profil` INT(1) NOT NULL,
  `date_creat` TIMESTAMP NOT NULL,
  `date_modif` TIMESTAMP NULL,
  `date_suppr` TIMESTAMP NULL,
  `fk_utilisateur` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `gnw_utilisateur.fk_utilisateur_idx` (`fk_utilisateur` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gnw`.`gnw_matiere`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gnw`.`gnw_matiere` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(255) NOT NULL,
  `date_creat` TIMESTAMP NOT NULL,
  `date_modif` TIMESTAMP NULL,
  `date_suppr` TIMESTAMP NULL,
  `fk_utilisateur` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `gnw_matiere.fk_utilisateur_idx` (`fk_utilisateur` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gnw`.`gnw_groupe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gnw`.`gnw_groupe` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(255) NOT NULL,
  `date_creat` TIMESTAMP NOT NULL,
  `date_modif` TIMESTAMP NULL,
  `date_suppr` TIMESTAMP NULL,
  `fk_utilisateur` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `gnw_groupe.fk_utilisateur_idx` (`fk_utilisateur` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gnw`.`gnw_formatexamen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gnw`.`gnw_formatexamen` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gnw`.`gnw_examen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gnw`.`gnw_examen` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `fk_professeur` INT(11) NOT NULL,
  `fk_format` INT(11) NOT NULL,
  `nom` VARCHAR(255) NOT NULL,
  `date` DATE NOT NULL,
  `fk_groupe` INT(11) NOT NULL,
  `fk_matiere` INT(11) NOT NULL,
  `coefficient` FLOAT NOT NULL,
  `moyenne` FLOAT NULL DEFAULT 0,
  `date_creat` TIMESTAMP NOT NULL,
  `date_modif` TIMESTAMP NULL,
  `date_suppr` TIMESTAMP NULL,
  `fk_utilisateur` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `gnw_examen_note.fk_utilisateur_idx` (`fk_utilisateur` ASC),
  INDEX `gnw_examen.fk_format_idx` (`fk_format` ASC),
  INDEX `gnw_examen.fk_professeur_idx` (`fk_professeur` ASC),
  INDEX `gnw_examen.fk_groupe_idx` (`fk_groupe` ASC),
  INDEX `gnw_examen.fk_matiere_idx` (`fk_matiere` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gnw`.`gnw_etudiant_groupe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gnw`.`gnw_etudiant_groupe` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `fk_etudiant` INT(11) NOT NULL,
  `fk_groupe` INT(11) NOT NULL,
  `date_creat` TIMESTAMP NOT NULL,
  `date_modif` TIMESTAMP NULL,
  `date_suppr` TIMESTAMP NULL,
  `fk_utilisateur` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `gnw_etudiant_groupe.fk_groupe_idx` (`fk_groupe` ASC),
  INDEX `gnw_etudiant_groupe.fk_etudiant_idx` (`fk_etudiant` ASC),
  INDEX `gnw_etudiant_groupe.fk_utilisateur_idx` (`fk_utilisateur` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gnw`.`gnw_professeur_matiere`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gnw`.`gnw_professeur_matiere` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `fk_professeur` INT(11) NOT NULL,
  `fk_matiere` INT(11) NOT NULL,
  `date_creat` TIMESTAMP NOT NULL,
  `date_modif` TIMESTAMP NULL,
  `date_suppr` TIMESTAMP NULL,
  `fk_utilisateur` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `gnw_professeur_matiere.fk_professeur_idx` (`fk_professeur` ASC),
  INDEX `gnw_professeur_matiere.fk_matiere_idx` (`fk_matiere` ASC),
  INDEX `gnw_professeur_matiere.fk_utilisateur_idx` (`fk_utilisateur` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gnw`.`gnw_professeur_groupe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gnw`.`gnw_professeur_groupe` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `fk_professeur` INT(11) NOT NULL,
  `fk_groupe` INT(11) NOT NULL,
  `date_creat` TIMESTAMP NOT NULL,
  `date_modif` TIMESTAMP NULL,
  `date_suppr` TIMESTAMP NULL,
  `fk_utilisateur` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `gnw_professeur_groupe.fk_professerur_idx` (`fk_professeur` ASC),
  INDEX `gnw_professeur_groupe.fk_groupe_idx` (`fk_groupe` ASC),
  INDEX `gnw_professeur_groupe.fk_utilisateur_idx` (`fk_utilisateur` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gnw`.`gnw_examen_note`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gnw`.`gnw_examen_note` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `note` FLOAT NULL,
  `fk_etudiant` INT(11) NOT NULL,
  `fk_examen` INT(11) NOT NULL,
  `date_creat` TIMESTAMP NOT NULL,
  `date_modif` TIMESTAMP NULL,
  `date_suppr` TIMESTAMP NULL,
  `fk_utilisateur` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `gnw_examen_note.fk_etudiant_idx` (`fk_etudiant` ASC),
  INDEX `gnw_examen_note.fk_examen_idx` (`fk_examen` ASC),
  INDEX `gnw_examen_note.fk_utilisateur_idx` (`fk_utilisateur` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
